export const GET_DASHBOARD_KEMENAG_DATA = "GET_DASHBOARD_KEMENAG_DATA"
export const GET_DASHBOARD_KEMENAG_DATA_SUCCESS = "GET_DASHBOARD_KEMENAG_DATA_SUCCESS"
export const GET_DASHBOARD_KEMENAG_DATA_FAIL = "GET_DASHBOARD_KEMENAG_DATA_FAIL"
